server:
  port: 9096

dubbo:
  registry:
    address: 47.105.72.216:2181
    protocol: zookeeper
    id: dubboProductServer
    client: curator
  metadata-report:
    address: zookeeper://47.105.72.216:2181
  application:
    name: hanfu-product-cosumer
  protocol:
    id: dubbo
    name: dubbo
  consumer:
    client: netty4

spring:
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.105.72.216:3306/user_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true  
    username: hanfu_admin
    password: Davin1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select now()
      idle-timeout: 3000000
      auto-commit: true
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
        keep-alive: 3600s


#
                                                                
logging:
  file: ./target/king-words.log  
